gantt

title Planificación
dateFormat  DD-MM-YYYY
excludes weekends

section Android
A task           :a1, 2d
A taskk           :a2, after a, 5dd
section Server
A task           :a1, 2d
A taskk           :a2, after a, 5dd